### ISSUE TITLE
How to help!

### ISSUE THREAD

**Issue by calebboyd** [Floobits/floobits-vscode#1]
My team uses floobits but we have to revert to intellij when we do instead of using the preferred vscode. Is there a roadmap or any plans to continue work on this? How can we help?

Update: Team is using VSCode LIveShare.

**Comment by Qwerp-Derp** [comment]
@ggreer Any plans?

**Comment by LmKupke** [comment]
@ggreer @kans my team would love floobits on vscode and/or visual studio.

**Comment by pumano** [comment]
@kans @ggreer any news about vscode plugin? It's will be released? Many people want to use it.

**Comment by peternavr** [comment]
Any updates?
