### ISSUE TITLE
Is this project work in progress?

### ISSUE THREAD

**Issue by yufeiminds** [Floobits/floobits-vscode#2]
Is this project work in progress? The latest commit is uploaded in 3 years ago.

I can't find it in vscode extensions

![image](https://user-images.githubusercontent.com/9150374/73510482-2ee94000-441d-11ea-9765-c3ada3046ce8.png)

**Comment by TJC** [comment]
Both the founder and co-founder now work elsewhere, so it doesn't look like it's still active.

**Comment by devinrhode2** [comment]
with this 'rona lockdown I think there's going to be people that will really benefit from completing this. I am one of those people - some co-workers at my new job use IntelliJ. I'd definitely put money on bountysource for this if someone were interested

**Comment by titaniumbones** [comment]
Happy to help out with tis,couldn't lead it -- if someone is working on it I'd love to test integration with Emacs.

**Comment by infinitesteps** [comment]
> with this 'rona lockdown I think there's going to be people that will really benefit from completing this. I am one of those people - some co-workers at my new job use IntelliJ. I'd definitely put money on bountysource for this if someone were interested

How much of a bounty? I could use a new boat! :-D

I just started using Floobits today from within CLion (IntelliJ) to share code with students during a live streamed class. It worked pretty well. In addition to vim and IntelliJ, I spend a lot of time in VSCodium. I don't have an immediate need but it'd be nice to have the option to connect fbits to VSCode/VSCodium some day.

**Comment by javierpr0** [comment]
It would be wonderful to have this plugin in an Editor like vscode. Intellij editors with each update are causing more bugs to the floobits plugin.

**Comment by yufeiminds** [comment]
Microsoft maintains an alternative called VSCode Live Share. It is my solution in 2023. So, I closed this issue.
